[tool.poetry]
name = "greek-dependency-trees"
version = "0.1.0"
description = ""
authors = ["James Tauber <jtauber@jtauber.com>"]

[tool.poetry.dependencies]
python = "^3.7"
lxml = "*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
